# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(12, 9, 9, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameSlider = QtWidgets.QSlider(self.centralwidget)
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName("frameSlider")
        self.horizontalLayout.addWidget(self.frameSlider)
        self.sliderLabel = QtWidgets.QLabel(self.centralwidget)
        self.sliderLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.sliderLabel.setText("")
        self.sliderLabel.setObjectName("sliderLabel")
        self.horizontalLayout.addWidget(self.sliderLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_Labels = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_Labels.setObjectName("dockWidget_Labels")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_Labels = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget_Labels.setMinimumSize(QtCore.QSize(250, 200))
        self.listWidget_Labels.setObjectName("listWidget_Labels")
        self.verticalLayout_3.addWidget(self.listWidget_Labels)
        self.dockWidget_Labels.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_Labels)
        self.dockWidget_Timeline = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_Timeline.setMinimumSize(QtCore.QSize(250, 102))
        self.dockWidget_Timeline.setObjectName("dockWidget_Timeline")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setMinimumSize(QtCore.QSize(120, 80))
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_Timeline = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_Timeline.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Timeline.setObjectName("verticalLayout_Timeline")
        self.dockWidget_Timeline.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_Timeline)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu.setTitle(_translate("MainWindow", "?"))
        self.dockWidget_Labels.setWindowTitle(_translate("MainWindow", "Labels"))
        self.dockWidget_Timeline.setWindowTitle(_translate("MainWindow", "Timeline"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

